version: '3.9'

services:

  redis:
    image: redis:7.0.5
    container_name: src-redis
    ports:
      - "6379:6379"
    # --save 20 10 # persist data every 20 second if at least 10 write operation are performed
    command: |
      redis-server
      --save 20 10
      --loglevel warning 
      --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - redis-data:/data

  spring-redis-caching:
    image: giangi/spring-redis-caching
    container_name: src-spring-redis-caching
    environment:
      REDIS_HOST: src-redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    ports:
      - "8090:8080"

volumes:
  redis-data:
    external: false